name: dart_lirc_client
description: Dart library for sending and receiving IR signals with lirc.
version: 0.0.1
#author: Jacob Bang <julemand101@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  ccompile: "^0.2.10"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
